### ISSUE TITLE
Crashing when pressing CTRL on home screen

### ISSUE THREAD

**Issue by applemes** [GabrielOlvH/Mo-Colors#1]
https://gyazo.com/d72ddf279d9010bae53e0bbf2d35a35e is the Not Enough Crashes Report

> ---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2021-03-04 00:26:52 CST
Description: Unexpected error

java.lang.NullPointerException
    at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.3)
    at me.steven.mocolors.utils.ColorUtils.getColor(ColorUtils.java:24)
    at me.steven.mocolors.MoColorsClient.lambda$onInitializeClient$5(MoColorsClient.java:94)
    at me.steven.mocolors.MoColorsClient$$Lambda$5160/14400466.onEndTick(Unknown Source)
    at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
    at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents$$Lambda$2785/2008413918.onEndTick(Unknown Source)
    at net.minecraft.client.MinecraftClient.handler$dco000$onEndTick(MinecraftClient:13886)
    at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1612)
    at net.minecraft.client.MinecraftClient.render(MinecraftClient:1021)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:681)
    at net.minecraft.client.MinecraftClient.handler$bpn000$afterCrashHandled(MinecraftClient:11404)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:704)
    at net.minecraft.client.main.Main.main(Main:215)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
    at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.16.5
  Minecraft Version ID: 1.16.5
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 2264295768 bytes (2159 MB) / 3254779904 bytes (3104 MB) up to 17179869184 bytes (16384 MB)
  CPUs: 4
  JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx16G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  Suspected Mods: Fabric Loader (fabricloader), Mo' Colors (mocolors), Fabric Lifecycle Events (v1) (fabric-lifecycle-events-v1)
  Fabric Mods: adabraniummod: Adabranium 1.3.2+1.16.5
               advancednbttooltip: Advanced NBT Tooltips 1.3.0+build.2-1.16.4
               altcraft-tools: Altcraft Tools 2.2.0
               angerable-patch: Angerable Patch 1.1.0-1.16.4
               appleskin: AppleSkin 1.0.11
               appliedenergistics2: Applied Energistics 2 8.1.0-alpha.13
               architectury: Architectury 1.8.130
               artifacts: Artifacts 2.2.1+fabric
               artifice: Artifice 0.14.4+1.16.3
               autoconfig1u: Auto Config v1 Updated 3.3.1
               beaconoverhaul: Beacon Overhaul 1.3.0+1.16
               beholdersvariations: Beholder's Variations 0.3.0
               betterbeds: Better Beds 1.1.0
               bettercaves: YUNG's Better Caves 1.16.5-1.1
               betterend: Better End 0.8.8-beta
               bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0
               betterthirdperson: Better Third Person 1.4.0
               bigbeacons: Big Beacons 1.0.1
               biomepicker: Biome Picker 1.1
               bitsandchisels: BitsAndChisels 1.1.8
               blockus: Blockus 2.1.0+1.16.5
               blue_endless_jankson: jankson 1.2.0
               bouncylife: Bouncy Life 1.1.8+mc1.16.4
               caelus: Caelus API 0.0.12-1.16.4
               campanion: Campanion 1.3.1+build.51
               can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.0.2
               cardinal-components-base: Cardinal Components API (base) 2.7.10
               cardinal-components-block: Cardinal Components API (blocks) 2.7.9
               cardinal-components-entity: Cardinal Components API (entities) 2.7.10
               cardinal-components-item: Cardinal Components API (items) 2.7.10
               carrier: Carrier 1.6.1
               celib: Celib - CebbyS Library Mod 0.3.1
               chainmail: Chainmail 0.5.0
               climbable: Climbable 0.2.0
               cloth-api: Cloth API 1.5.47
               cloth-armor-api-v1: Cloth Armor API v1 1.5.47
               cloth-basic-math: Cloth Basic Math 0.5.1
               cloth-client-events-v0: Cloth Client Events v0 1.5.47
               cloth-common-events-v1: Cloth Common Events v1 1.5.47
               cloth-config2: Cloth Config v4 4.11.14
               cloth-datagen-api-v1: Cloth Datagen v1 1.5.47
               cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.5.47
               cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.5.47
               cloth-scissors-api-v1: Cloth Scissors API v1 1.5.47
               cloth-utils-v1: Cloth Utils v1 1.5.47
               colytra: Colytra 1.3.0-1.16.4
               com_github_mouse0w0_fastreflection: FastReflection 1.0.1
               com_squareup_moshi_moshi: moshi 1.9.2
               com_squareup_okio_okio: okio 1.16.0
               complete_bone_meal: Complete Bone Meal 1.0.0
               consistency_plus: Consistency Plus 0.1.0
               cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
               craftingpad: Crafting Pad 1.16.4-fabric0.25.1-1.0.5
               crowdin-translate: CrowdinTranslate 1.2
               customportalapi: customportalapi 0.0.1-beta23-1.16
               dark-loading-screen: Dark Loading Screen 1.6.2
               dawn: Dawn API 1.6.1
               deep-dungeons: Deep Dungeons 1.0.0-1.16.5
               ducts: Ducts 1.0.4
               dungeonsmod: Dungeons Mod Lite 1.16.5-1.0.0
               earthtojavamobs: Earth2Java 1.6.1+1.16.4
               elevator: Elevator Mod 1.0.0
               elytraboosters: Elytra Boosters Mod 1.1.0
               enhancedcelestials: Enhanced Celestials 1.0.1
               expandedstorage: ExpandedStorage 5.6.32
               extraalchemy: Extra Alchemy 1.3.1
               fabric: Fabric API 0.31.0+1.16
               fabric-api-base: Fabric API Base 0.2.1+9354966b7d
               fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
               fabric-command-api-v1: Fabric Command API (v1) 1.1.0+f9b3753b7d
               fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
               fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
               fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
               fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
               fabric-furnaces: Fabric Furnaces 1.3.3-1.16.4
               fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
               fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
               fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
               fabric-language-kotlin: Fabric Language Kotlin 1.4.21+build.1
               fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
               fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
               fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
               fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
               fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
               fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
               fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
               fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
               fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
               fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
               fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
               fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
               fabrication: Fabrication 1.3.3
               fabricloader: Fabric Loader 0.11.2
               fairenchanting: FairEnchanting 1.2.0
               fallflyinglib: FallFlyingLib 1.1.0
               falling_tree: FallingTree 2.10.0
               fenceplayerupper: Fence Player Upper 1.1.2+21w05b
               fiber: fiber 0.23.0-2
               flytre_lib: FlytreLib 0.2.8
               funnel: Funnel 1.0.0
               glassential: Glassential 1.16.4-1.1.5
               goldensteak: Goldensteak 1.0.2
               golemsgalore: Golems Galore 0.2.0+mc.1.16.2
               greater_eye: Greater Eye of Ender 1.1.5
               hplus: Better Hoppers (Hopper+) 2.2.0
               indrev: Industrial Revolution 1.7.15-BETA
               infinitywaterbucket: Infinity Water Bucket 1.0.3.2-compat-mc1.16.4-fabric
               instantlava: InstantLava 1.2.1
               inventorysorter: Inventory Sorter 1.7.6-1.16
               itemscroller: Item Scroller 0.15.0-dev.20210111.205029
               jankson: Jankson 3.0.1+j1.2.0
               java: Java HotSpot(TM) 64-Bit Server VM 8
               jumpoverfences: JumpOverFences 1.16-0.0.3
               kibe: Kibe 1.6.2-BETA
               kubejs: KubeJS 1.5.5
               kyrptconfig: Kytpt Config 1.1.6-1.16
               lakeside: Lakeside 1.0.3+1.16.4
               lapisreserve: Lapis Reserve 1.0.6
               libblockattributes: LibBlockAttributes 0.8.5
               libblockattributes_core: LibBlockAttributes (Core) 0.8.5
               libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.5
               libblockattributes_items: LibBlockAttributes (Items) 0.8.5
               libcd: LibCapableData 3.0.3+1.16.3
               libgui: LibGui 3.3.5+1.16.5
               lifts: Lifts 1.0.2-BETA
               lightoverlay: Light Overlay 5.6.1
               loadcatcher: Entrypoint Catcher 2.0.0
               loading-timer: Loading Timer 1.1.1
               magic_lanterns: Magic Lanterns 1.4.4
               magna: Magna 1.4.3-1.16.2
               malilib: MaLiLib 0.10.0-dev.21+arne.2
               minecraft: Minecraft 1.16.5
               minegate-moreblocks: MineGate - MoreBlocks 1.0.2
               mining_dims: Mining Dimensions 1.0.4
               mobfarmutilities: Mob Farm Utilities 1.2.1
               mocolors: Mo' Colors 1.1.0
               modmenu: Mod Menu 1.16.8
               modupdater: ModUpdater 1.1.11+1.16.2-rc2
               moenchantments: Mo'Enchantments 1.13.8
               more_gems: More Gems 1.1.22
               mostructures: Mo' Structures 1.0.1+mc.1.16.4
               mutuality: Mutuality 1.0.0
               no_fog: No Fog 1.0.2-beta.1+1.16.2
               noenchantcap: NoEnchantCap 2.0.0
               nookbuild: NookBuild 1.2.1
               notenoughcrashes: Not Enough Crashes 2.1.4+1.16.4
               notramplefabric: NoTrample 1.0.0
               orderly: Orderly 2.0.0-alpha.10-1.16
               org_jetbrains_annotations: annotations 20.0.0
               org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.21
               org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.21
               org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.21
               org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.21
               org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
               org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
               overpowered_pickles: Overpowered Pickles 1.1.2
               packed: Packed Storage 1.0.9
               packed_cobblestone: Packed Cobblestone 1.0.0
               patchouli: Patchouli 1.16.4-48-FABRIC
               phosphor: Phosphor 0.7.0+build.10
               plantinajar: Plant In A Jar 1.8.1
               playerabilitylib: Pal 1.2.1
               playerless: playerless final
               polymorph: Polymorph 0.0.10-1.16.5
               pride: Pride Lib 1.0.0+1.16
               quickshulker: Quick Shulker 1.1.11-1.16
               reach-entity-attributes: Reach Entity Attributes 1.1.0
               reborncore: Reborn Core 4.6.4+build.117
               repurposed_structures: Repurposed Structures 1.16.4-1.7.4
               reroll: Reroll 1.1.0-1.16.4
               ring_of_attraction: Ring Of Attraction 1.0.29
               ring_of_enderchest: Ring of Enderchest 1.0.27
               ring_of_miner: Ring Of Miner 1.1.2
               riverredux: River Redux 0.1.5
               roughlyenoughitems: Roughly Enough Items 5.10.184
               roughlyenoughitems-api: REI (API) 5.10.184
               roughlyenoughitems-default-plugin: REI (Default Plugin) 5.10.184
               roughlyenoughitems-runtime: REI (Runtime) 5.10.184
               roughlyenoughresources: Roughly Enough Resources 2.1.3
               shulkerboxtooltip: Shulker Box Tooltip 2.3.4+1.16.4
               silky_spawners: Silky Spawners 2.1.0+build.2-1.16
               simplelife: SimpleLife 0.0.7
               slabref: Refabricated Slabs 0.3.1
               slightlyvanilla: SlightlyVanilla 1.0.12+1.16.4
               stacc: Stacc 1.0.1
               staffofbuilding: Staff of Building 1.2.4-1.16.2
               starry_sky: Starry Skies 1.0.9-1.16.5
               static-content: Static Content 1.0.1-1.16.2
               staticdata: Static Data 1.1.2
               step-height-entity-attribute: Step Height Entity Attribute 1.0.0
               structurized: Structurized 1.1.0
               team_reborn_energy: Energy 0.1.1
               techreborn: Tech Reborn 3.7.3+build.192
               terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.0+build.4
               terraform-tree-api-v1: Terraform Tree API (v1) 1.0.1+build.4
               tinytweaks: TinyTweaks 1.2.3
               tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
               toms_storage: Tom's Simple Storage Mod 1.1.8
               totemmod: Wither Totems Mod 0.3.2
               trees-do-not-float: Trees Do Not Float 2.1.128
               trinkets: Trinkets 2.6.7
               tweed: Tweed API 3.0.0-beta.15
               vanilla-hammers: Vanilla Hammers 3.0.1-1.16.3
               vanillaenhanced: VanillaEnhanced 1.3.1
               vanillaexcavators: Vanilla Excavators 1.1.0
               voyager: Voyager 1.0.0
               waila: Hwyla 1.9.22
               winged: Winged Mod 1.16.2-1.4.1
               xaerominimap: Xaero's Minimap 21.1.0
               xaeroworldmap: Xaero's World Map 1.11.9
               xlpackets: XLPackets 1.1
               yungsapi: YUNG's API 1.16.5-Fabric-2
  Patchouli open book context: n/a
  Launched Version: fabric-loader-0.11.2-1.16.5
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: GeForce RTX 3070/PCIe/SSE2 GL version 4.6.0 NVIDIA 461.72, NVIDIA Corporation
  GL Caps: Using framebuffer using OpenGL 3.0
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fabric'
  Type: Client (map_client.txt)
  Graphics mode: fast
  Resource Packs: vanilla, Fabric Mods, kubejs:resource_pack (incompatible), file/x32 Clear Glass 1.16.2, file/Vanilla Tweaks ResourcePack
  Current Language: English (US)
  CPU: 4x Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
  Client Crashes Since Restart: 2
  Integrated Server Crashes Since Restart: 0

**Comment by GabrielOlvH** [comment]
Fixed as of 1.1.1
