### ISSUE TITLE
Compatibility with Immersive Portals?

### ISSUE THREAD

**Issue by R3ddAG** [GabrielOlvH/Mo-Colors#5]
Every time I try to load this mod with ModMenu and Immersive Portals, the game crashes and leaves this report:
https://pastebin.com/XxNStJHt

**Comment by RemagOfficial** [comment]
not sure if it fixes anything but IP comes with modmenu

**Comment by R3ddAG** [comment]
Update: I ended up using the 1.17.0 installation of Fabric, and the game stopped crashing.
